// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2026, 3:47:41 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/user/maslahattani-v2/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/maslahattani-v2/frontend/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/maslahattani-v2/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/maslahattani-v2/frontend/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/maslahattani-v2/frontend/src/plugins/**/*.{js,ts,mjs}","C:/Users/user/maslahattani-v2/frontend/src/composables/**/*.{js,ts,mjs}","C:/Users/user/maslahattani-v2/frontend/src/utils/**/*.{js,ts,mjs}","C:/Users/user/maslahattani-v2/frontend/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/maslahattani-v2/frontend/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/maslahattani-v2/frontend/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/maslahattani-v2/frontend/src/app.config.{js,ts,mjs}","C:/Users/user/maslahattani-v2/frontend/app/spa-loading-template.html"]}},
{"theme":{"extend":{"colors":{"brand":{"50":"#eff6ff","100":"#dbeafe","200":"#bfdbfe","300":"#93c5fd","400":"#60a5fa","500":"#3b82f6","600":"#2563eb","700":"#1d4ed8","800":"#1e40af","900":"#1e3a8a"}}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;